version: '3.8'

services:
  app:
    image: ghcr.io/jeon-dom/docker-password-gen:1.0.0
    networks:
      - traefik-public
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        # Configuración exclusiva para tu subdominio: password.byronrm.com
        - "traefik.http.routers.domenica-password-router.entrypoints=http"
        - "traefik.http.routers.domenica-password-router.rule=Host(`password.byronrm.com`)"
        - "traefik.http.middlewares.domenica-password-redirect.redirectscheme.scheme=https"
        # CORREGIDO: Ahora el router coincide perfectamente con el de arriba
        - "traefik.http.routers.domenica-password-router.middlewares=domenica-password-redirect"
        
        - "traefik.http.routers.domenica-password-secure.entrypoints=https"
        - "traefik.http.routers.domenica-password-secure.rule=Host(`password.byronrm.com`)"
        - "traefik.http.routers.domenica-password-secure.tls=true"
        - "traefik.http.routers.domenica-password-secure.tls.certresolver=http"
        - "traefik.http.routers.domenica-password-secure.service=domenica-password-service"
        
        # Traefik redirige el tráfico al puerto 5000 interno de tu Flask
        - "traefik.http.services.domenica-password-service.loadbalancer.server.port=5000"
        - "traefik.docker.network=traefik-public"

networks:
  traefik-public:
    external: true